#############################################################################
# Makefile for building: Red_Panda_CPP
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  Red_Panda_CPP.pro
# Template: subdirs
# Command: /usr/lib/qt5/bin/qmake -o Makefile Red_Panda_CPP.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Red_Panda_CPP1.0.0
DISTDIR = /home/voladsky/mmcs/compilers/RedPanda-PABC/.tmp/Red_Panda_CPP1.0.0
SUBTARGETS    =  \
		sub-RedPandaIDE \
		sub-tools-consolepauser \
		sub-libs-redpanda_qt_utils \
		sub-libs-qsynedit \
		sub-libs-lua


sub-RedPandaIDE-qmake_all: sub-tools-consolepauser-qmake_all sub-libs-qsynedit-qmake_all sub-libs-lua-qmake_all FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro
	cd RedPandaIDE/ && $(MAKE) -f Makefile qmake_all
sub-RedPandaIDE: sub-tools-consolepauser \
		sub-libs-qsynedit \
		sub-libs-lua FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile
sub-RedPandaIDE-make_first: sub-tools-consolepauser-make_first sub-libs-qsynedit-make_first sub-libs-lua-make_first FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile 
sub-RedPandaIDE-all: sub-tools-consolepauser-all sub-libs-qsynedit-all sub-libs-lua-all FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile all
sub-RedPandaIDE-clean: sub-tools-consolepauser-clean sub-libs-qsynedit-clean sub-libs-lua-clean FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile clean
sub-RedPandaIDE-distclean: sub-tools-consolepauser-distclean sub-libs-qsynedit-distclean sub-libs-lua-distclean FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile distclean
sub-RedPandaIDE-install_subtargets: sub-tools-consolepauser-install_subtargets sub-libs-qsynedit-install_subtargets sub-libs-lua-install_subtargets FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile install
sub-RedPandaIDE-uninstall_subtargets: sub-tools-consolepauser-uninstall_subtargets sub-libs-qsynedit-uninstall_subtargets sub-libs-lua-uninstall_subtargets FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile uninstall
sub-tools-consolepauser-qmake_all:  FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro
	cd tools/consolepauser/ && $(MAKE) -f Makefile qmake_all
sub-tools-consolepauser: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile
sub-tools-consolepauser-make_first: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile 
sub-tools-consolepauser-all: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile all
sub-tools-consolepauser-clean: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile clean
sub-tools-consolepauser-distclean: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile distclean
sub-tools-consolepauser-install_subtargets: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile install
sub-tools-consolepauser-uninstall_subtargets: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile uninstall
sub-libs-redpanda_qt_utils-qmake_all:  FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro
	cd libs/redpanda_qt_utils/ && $(MAKE) -f Makefile qmake_all
sub-libs-redpanda_qt_utils: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile
sub-libs-redpanda_qt_utils-make_first: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile 
sub-libs-redpanda_qt_utils-all: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile all
sub-libs-redpanda_qt_utils-clean: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile clean
sub-libs-redpanda_qt_utils-distclean: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile distclean
sub-libs-redpanda_qt_utils-install_subtargets: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile install
sub-libs-redpanda_qt_utils-uninstall_subtargets: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile uninstall
sub-libs-qsynedit-qmake_all: sub-libs-redpanda_qt_utils-qmake_all FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro
	cd libs/qsynedit/ && $(MAKE) -f Makefile qmake_all
sub-libs-qsynedit: sub-libs-redpanda_qt_utils FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile
sub-libs-qsynedit-make_first: sub-libs-redpanda_qt_utils-make_first FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile 
sub-libs-qsynedit-all: sub-libs-redpanda_qt_utils-all FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile all
sub-libs-qsynedit-clean: sub-libs-redpanda_qt_utils-clean FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile clean
sub-libs-qsynedit-distclean: sub-libs-redpanda_qt_utils-distclean FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile distclean
sub-libs-qsynedit-install_subtargets: sub-libs-redpanda_qt_utils-install_subtargets FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile install
sub-libs-qsynedit-uninstall_subtargets: sub-libs-redpanda_qt_utils-uninstall_subtargets FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile uninstall
sub-libs-lua-qmake_all:  FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro
	cd libs/lua/ && $(MAKE) -f Makefile qmake_all
sub-libs-lua: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile
sub-libs-lua-make_first: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile 
sub-libs-lua-all: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile all
sub-libs-lua-clean: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile clean
sub-libs-lua-distclean: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile distclean
sub-libs-lua-install_subtargets: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile install
sub-libs-lua-uninstall_subtargets: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile uninstall

Makefile: Red_Panda_CPP.pro .qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		version.inc \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Red_Panda_CPP.pro \
		platform/linux/RedPandaIDE.desktop.in
	$(QMAKE) -o Makefile Red_Panda_CPP.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
version.inc:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Red_Panda_CPP.pro:
platform/linux/RedPandaIDE.desktop.in:
qmake: FORCE
	@$(QMAKE) -o Makefile Red_Panda_CPP.pro

qmake_all: sub-RedPandaIDE-qmake_all sub-tools-consolepauser-qmake_all sub-libs-redpanda_qt_utils-qmake_all sub-libs-qsynedit-qmake_all sub-libs-lua-qmake_all FORCE

make_first: sub-RedPandaIDE-make_first sub-tools-consolepauser-make_first sub-libs-redpanda_qt_utils-make_first sub-libs-qsynedit-make_first sub-libs-lua-make_first  FORCE
all: sub-RedPandaIDE-all sub-tools-consolepauser-all sub-libs-redpanda_qt_utils-all sub-libs-qsynedit-all sub-libs-lua-all  FORCE
clean: sub-RedPandaIDE-clean sub-tools-consolepauser-clean sub-libs-redpanda_qt_utils-clean sub-libs-qsynedit-clean sub-libs-lua-clean  FORCE
distclean: sub-RedPandaIDE-distclean sub-tools-consolepauser-distclean sub-libs-redpanda_qt_utils-distclean sub-libs-qsynedit-distclean sub-libs-lua-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash /home/voladsky/mmcs/compilers/RedPanda-PABC/platform/linux/RedPandaIDE.desktop
install_subtargets: sub-RedPandaIDE-install_subtargets sub-tools-consolepauser-install_subtargets sub-libs-redpanda_qt_utils-install_subtargets sub-libs-qsynedit-install_subtargets sub-libs-lua-install_subtargets FORCE
uninstall_subtargets: sub-RedPandaIDE-uninstall_subtargets sub-tools-consolepauser-uninstall_subtargets sub-libs-redpanda_qt_utils-uninstall_subtargets sub-libs-qsynedit-uninstall_subtargets sub-libs-lua-uninstall_subtargets FORCE

sub-RedPandaIDE-check: sub-tools-consolepauser-check sub-libs-qsynedit-check sub-libs-lua-check
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile check
sub-tools-consolepauser-check:
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile check
sub-libs-redpanda_qt_utils-check:
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile check
sub-libs-qsynedit-check: sub-libs-redpanda_qt_utils-check
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile check
sub-libs-lua-check:
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile check
check: sub-RedPandaIDE-check sub-tools-consolepauser-check sub-libs-redpanda_qt_utils-check sub-libs-qsynedit-check sub-libs-lua-check

sub-RedPandaIDE-benchmark: sub-tools-consolepauser-benchmark sub-libs-qsynedit-benchmark sub-libs-lua-benchmark
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -f Makefile benchmark
sub-tools-consolepauser-benchmark:
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -f Makefile benchmark
sub-libs-redpanda_qt_utils-benchmark:
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -f Makefile benchmark
sub-libs-qsynedit-benchmark: sub-libs-redpanda_qt_utils-benchmark
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -f Makefile benchmark
sub-libs-lua-benchmark:
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-RedPandaIDE-benchmark sub-tools-consolepauser-benchmark sub-libs-redpanda_qt_utils-benchmark sub-libs-qsynedit-benchmark sub-libs-lua-benchmark
install_resources: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/RedPandaCPP || mkdir -p $(INSTALL_ROOT)/usr/local/share/RedPandaCPP
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/platform/linux/templates $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/templates

uninstall_resources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/templates
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/ 


install_docs: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP || mkdir -p $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/README.md $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/README.md
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/NEWS.md $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/NEWS.md
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/LICENSE $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/LICENSE

uninstall_docs: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/LICENSE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/NEWS.md
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/README.md
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/doc/RedPandaCPP/ 


install_xdgicons: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/icons/hicolor/scalable/apps/ || mkdir -p $(INSTALL_ROOT)/usr/local/share/icons/hicolor/scalable/apps/
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/platform/linux/redpandaide.svg $(INSTALL_ROOT)/usr/local/share/icons/hicolor/scalable/apps/redpandaide.svg

uninstall_xdgicons: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/icons/hicolor/scalable/apps/redpandaide.svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/icons/hicolor/scalable/apps/ 


install_desktop: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/applications || mkdir -p $(INSTALL_ROOT)/usr/local/share/applications
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/platform/linux/RedPandaIDE.desktop $(INSTALL_ROOT)/usr/local/share/applications/RedPandaIDE.desktop

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/applications/RedPandaIDE.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/applications/ 


install_mime: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/mime/packages || mkdir -p $(INSTALL_ROOT)/usr/local/share/mime/packages
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/platform/linux/redpandaide.xml $(INSTALL_ROOT)/usr/local/share/mime/packages/redpandaide.xml

uninstall_mime: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/mime/packages/redpandaide.xml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/mime/packages/ 


install_pabcnet: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux || mkdir -p $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/AsyncIO.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/AsyncIO.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/CodeCompletion.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeCompletion.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Compiler.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Compiler.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/CompilerTools.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerTools.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Debugger.Core.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Debugger.Core.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Errors.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Errors.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Highlighting $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Highlighting
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ICSharpCode.Core.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.Core.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ICSharpCode.Core.WinForms.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.Core.WinForms.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ICSharpCode.NRefactory.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.NRefactory.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ICSharpCode.SharpDevelop.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.SharpDevelop.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ICSharpCode.SharpDevelop.Dom.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.SharpDevelop.Dom.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ICSharpCode.TextEditorLinux.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.TextEditorLinux.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LambdaAnySynToSemConverter.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LambdaAnySynToSemConverter.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LanguageIntegrator.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageIntegrator.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LanguageKits $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageKits
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lib $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Lib
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LibSource
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Lng
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Localization.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Localization.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Microsoft.Bcl.HashCode.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Microsoft.Bcl.HashCode.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Microsoft.Scripting.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Microsoft.Scripting.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Mono.Cecil.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Mono.Cecil.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Mono.Debugger.Soft.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Mono.Debugger.Soft.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/NETGenerator.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NETGenerator.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/NetMQ.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NetMQ.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/OptimizerConversion.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/OptimizerConversion.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/pabcnetc.exe $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetc.exe
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/pabcnetc.exe.config $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetc.exe.config
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/pabcnetcclear.exe $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetcclear.exe
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/pabcnetcclear.exe.config $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetcclear.exe.config
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ParserTools.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ParserTools.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/PascalABCLanguageInfo.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCLanguageInfo.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/PascalABCNET.chm $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNET.chm
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/PascalABCNETLinux.exe $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNETLinux.exe
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/PascalABCNETLinux.exe.config $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNETLinux.exe.config
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/PascalABCParser.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCParser.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Pause.exe $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Pause.exe
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/PluginsSupportLinux.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PluginsSupportLinux.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/ProgrammRunner.exe $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ProgrammRunner.exe
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/SemanticTree.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticTree.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/StringConstants.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/StringConstants.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/SyntaxTree.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTree.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/SyntaxTreeConverters.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeConverters.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/SyntaxVisitors.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxVisitors.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Buffers.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Buffers.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Collections.Immutable.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Collections.Immutable.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Formats.Nrbf.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Formats.Nrbf.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Memory.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Memory.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Numerics.Vectors.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Numerics.Vectors.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Reflection.Metadata.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Reflection.Metadata.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Resources.Extensions.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Resources.Extensions.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.Runtime.CompilerServices.Unsafe.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Runtime.CompilerServices.Unsafe.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/System.ValueTuple.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.ValueTuple.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/TeacherControlPlugin.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/TeacherControlPlugin.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/template.pct $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/template.pct
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/TreeConverter.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/TreeConverter.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/WeifenLuo.WinFormsUI.Docking.ThemeVS2005Linux.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/WeifenLuo.WinFormsUI.Docking.ThemeVS2005Linux.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/WeifenLuo.WinFormsUI.DockingLinux.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/WeifenLuo.WinFormsUI.DockingLinux.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/YieldHelpers.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/YieldHelpers.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Highlighting/PascalABCNET.xshd $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNET.xshd
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lib/GraphABC.pcu $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABC.pcu
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lib/GraphABCHelper.pcu $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABCHelper.pcu
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lib/nunit.framework.dll $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/nunit.framework.dll
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lib/PABCExtensions.pcu $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCExtensions.pcu
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lib/PABCSystem.pcu $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCSystem.pcu
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/__RedirectIOMode.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/__RedirectIOMode.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/__RunMode.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/__RunMode.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/ABCDatabases.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ABCDatabases.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/ABCObjects.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ABCObjects.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/BBCMicrobit.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/BBCMicrobit.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/ClientServer.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ClientServer.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Core.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Core.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Countries.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Countries.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/CRT.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CRT.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/DMCollect.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DMCollect.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/DMTaskMaker.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DMTaskMaker.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/DMZadan.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DMZadan.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Drawman.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Drawman.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/DrawManField.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DrawManField.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/FilesOperations.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/FilesOperations.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/FormsABC.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/FormsABC.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/GraphABC.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABC.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/GraphABCHelper.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABCHelper.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/IniFile.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/IniFile.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/LightPT.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LightPT.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/NumLibABC.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NumLibABC.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/NUnitABC.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NUnitABC.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/PABCExtensions.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCExtensions.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/PABCSystem.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCSystem.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/PointerTools.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PointerTools.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Robot.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Robot.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/RobotField.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RobotField.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/RobotTaskMaker.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RobotTaskMaker.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/RobotZadan.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RobotZadan.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/School.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/School.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/SF.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SF.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Sounds.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Sounds.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Speech.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Speech.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Tasks.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Tasks.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Timers.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Timers.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Turtle.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Turtle.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/TwoPanelsWindow.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/TwoPanelsWindow.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/XLSX.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/XLSX.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Ð Ð¾Ð±Ð¾Ñ.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Ð Ð¾Ð±Ð¾Ñ.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/LibSource/Ð§ÐµÑÑÐµÐ¶Ð½Ð¸Ðº.pas $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Ð§ÐµÑÑÐµÐ¶Ð½Ð¸Ðº.pas
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Eng
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Rus
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/AspectsTree.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/AspectsTree.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/CodeCompletion.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeCompletion.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/CodeTemplates.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeTemplates.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/CompilerController.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerController.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/CompilerErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/Global_loc.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Global_loc.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/InternalErrorReport.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/InternalErrorReport.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/LanguageName.info $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageName.info
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/OpenMPErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/OpenMPErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/PABCNETC.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCNETC.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/ParserErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ParserErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/PascalABCParser.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCParser.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/PT4Provider.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PT4Provider.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/RuntimeExceptions_ds.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RuntimeExceptions_ds.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_ds.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ds.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_ib.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ib.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_ms.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ms.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_nv.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_nv.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_rs.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_rs.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_ssyy.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ssyy.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SemanticErrors_ws.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ws.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SyantaxTreeVisualisator.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyantaxTreeVisualisator.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/SyntaxTreeVisitorsErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeVisitorsErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/VisualPascalABCNET.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/VisualPascalABCNET_VEC.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET_VEC.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/Warning_ib.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warning_ib.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Eng/Warnings_ds.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warnings_ds.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/_Global $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/_Global
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/_Global_loc $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/_Global_loc
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/AspectsTree.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/AspectsTree.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/CodeCompletion.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeCompletion.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/CodeTemplates.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeTemplates.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/CompilerController.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerController.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/CompilerErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/HelpBuilder.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/HelpBuilder.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/InternalErrorReport.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/InternalErrorReport.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/KuMirParser.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/KuMirParser.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/LanguageConvertor.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageConvertor.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/LanguageName.info $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageName.info
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/OpenMPErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/OpenMPErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/PABCNETC.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCNETC.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/ParserErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ParserErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/PascalABCParser.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCParser.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/PluginController.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PluginController.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/PT4Provider.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PT4Provider.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/PythonABCParser.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PythonABCParser.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/RegisterAndControlPlugin.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RegisterAndControlPlugin.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/RuntimeExceptions_ds.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RuntimeExceptions_ds.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_ds.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ds.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_ib.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ib.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_ms.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ms.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_nv.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_nv.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_rs.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_rs.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_ssyy.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ssyy.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticErrors_ws.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ws.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SemanticTreeVisualisator.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticTreeVisualisator.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SourceTextFormater.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SourceTextFormater.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SyntaxTreeVisitorsErrors.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeVisitorsErrors.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/SyntaxTreeVisualisator.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeVisualisator.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/VisualPascalABCNET.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/VisualPascalABCNET_VEC.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET_VEC.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/Warning_ib.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warning_ib.dat
	$(QINSTALL) /home/voladsky/mmcs/compilers/RedPanda-PABC/PascalABCNETLinux/Lng/Rus/Warnings_ds.dat $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warnings_ds.dat

uninstall_pabcnet: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warnings_ds.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warning_ib.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET_VEC.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeVisualisator.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeVisitorsErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SourceTextFormater.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticTreeVisualisator.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ws.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ssyy.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_rs.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_nv.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ms.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ib.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ds.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RuntimeExceptions_ds.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RegisterAndControlPlugin.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PythonABCParser.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PT4Provider.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PluginController.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCParser.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ParserErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCNETC.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/OpenMPErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageName.info
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageConvertor.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/KuMirParser.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/InternalErrorReport.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/HelpBuilder.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerController.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeTemplates.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeCompletion.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/AspectsTree.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/_Global_loc
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/_Global
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warnings_ds.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Warning_ib.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET_VEC.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/VisualPascalABCNET.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeVisitorsErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyantaxTreeVisualisator.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ws.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ssyy.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_rs.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_nv.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ms.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ib.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticErrors_ds.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RuntimeExceptions_ds.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PT4Provider.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCParser.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ParserErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCNETC.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/OpenMPErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageName.info
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/InternalErrorReport.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Global_loc.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerErrors.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerController.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeTemplates.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeCompletion.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/AspectsTree.dat
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Rus
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Eng
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Ð§ÐµÑÑÐµÐ¶Ð½Ð¸Ðº.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Ð Ð¾Ð±Ð¾Ñ.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/XLSX.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/TwoPanelsWindow.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Turtle.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Timers.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Tasks.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Speech.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Sounds.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SF.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/School.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RobotZadan.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RobotTaskMaker.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/RobotField.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Robot.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PointerTools.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCSystem.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCExtensions.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NUnitABC.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NumLibABC.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LightPT.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/IniFile.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABCHelper.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABC.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/FormsABC.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/FilesOperations.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DrawManField.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Drawman.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DMZadan.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DMTaskMaker.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/DMCollect.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CRT.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Countries.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Core.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ClientServer.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/BBCMicrobit.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ABCObjects.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ABCDatabases.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/__RunMode.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/__RedirectIOMode.pas
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCSystem.pcu
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PABCExtensions.pcu
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/nunit.framework.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABCHelper.pcu
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/GraphABC.pcu
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNET.xshd
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/YieldHelpers.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/WeifenLuo.WinFormsUI.DockingLinux.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/WeifenLuo.WinFormsUI.Docking.ThemeVS2005Linux.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/TreeConverter.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/template.pct
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/TeacherControlPlugin.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.ValueTuple.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Runtime.CompilerServices.Unsafe.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Resources.Extensions.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Reflection.Metadata.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Numerics.Vectors.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Memory.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Formats.Nrbf.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Collections.Immutable.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/System.Buffers.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxVisitors.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTreeConverters.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SyntaxTree.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/StringConstants.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/SemanticTree.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ProgrammRunner.exe
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PluginsSupportLinux.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Pause.exe
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCParser.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNETLinux.exe.config
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNETLinux.exe
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCNET.chm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/PascalABCLanguageInfo.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ParserTools.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetcclear.exe.config
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetcclear.exe
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetc.exe.config
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/pabcnetc.exe
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/OptimizerConversion.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NetMQ.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/NETGenerator.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Mono.Debugger.Soft.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Mono.Cecil.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Microsoft.Scripting.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Microsoft.Bcl.HashCode.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Localization.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Lng
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LibSource
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Lib
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageKits
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LanguageIntegrator.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/LambdaAnySynToSemConverter.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.TextEditorLinux.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.SharpDevelop.Dom.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.SharpDevelop.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.NRefactory.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.Core.WinForms.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ICSharpCode.Core.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Highlighting
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Errors.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Debugger.Core.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CompilerTools.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/Compiler.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/CodeCompletion.dll
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/AsyncIO.dll
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/RedPandaCPP/PascalABCNETLinux/ 


install:install_subtargets install_resources install_docs install_xdgicons install_desktop install_mime install_pabcnet  FORCE

uninstall: uninstall_resources uninstall_docs uninstall_xdgicons uninstall_desktop uninstall_mime uninstall_pabcnet uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-RedPandaIDE-distdir sub-tools-consolepauser-distdir sub-libs-redpanda_qt_utils-distdir sub-libs-qsynedit-distdir sub-libs-lua-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.conf version.inc Red_Panda_CPP.pro $(DISTDIR)/

sub-RedPandaIDE-distdir: FORCE
	@test -d RedPandaIDE/ || mkdir -p RedPandaIDE/
	cd RedPandaIDE/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/RedPandaIDE/RedPandaIDE.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/RedPandaIDE

sub-tools-consolepauser-distdir: FORCE
	@test -d tools/consolepauser/ || mkdir -p tools/consolepauser/
	cd tools/consolepauser/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/tools/consolepauser/consolepauser.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/tools/consolepauser

sub-libs-redpanda_qt_utils-distdir: FORCE
	@test -d libs/redpanda_qt_utils/ || mkdir -p libs/redpanda_qt_utils/
	cd libs/redpanda_qt_utils/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/redpanda_qt_utils/redpanda_qt_utils.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/libs/redpanda_qt_utils

sub-libs-qsynedit-distdir: FORCE
	@test -d libs/qsynedit/ || mkdir -p libs/qsynedit/
	cd libs/qsynedit/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/qsynedit/qsynedit.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/libs/qsynedit

sub-libs-lua-distdir: FORCE
	@test -d libs/lua/ || mkdir -p libs/lua/
	cd libs/lua/ && ( test -e Makefile || $(QMAKE) -o Makefile /home/voladsky/mmcs/compilers/RedPanda-PABC/libs/lua/lua.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/libs/lua

